### ISSUE TITLE
Error saving dam param

### ISSUE THREAD

**Issue by FitsumW** [global-hydrodynamics/CaMa-Flood_v4#82]
I am testing the reservoir operation module and I found a minor issue in trying to save the dam parameters in the following line of code:  i.e, is the column name 'year' supposed to be in the list as the 'damcsv2' dataframe does not have the year column? 

https://github.com/global-hydrodynamics/CaMa-Flood_v4/blob/3d80effeff18739da429807e36255c9cfeecce67/map/src/src_dam/script/complete_damcsv.py#L114

**Comment by bigasmountain** [comment]
This is fixed in the latest version (v4.2). The construction year is used in Year-by-Year option in the new reservoir operation scheme.
