### ISSUE TITLE
Permission Denied Error When Configuring test1-glb_15min.sh

### ISSUE THREAD

**Issue by siddigberama999** [global-hydrodynamics/CaMa-Flood_v4#84]
I am encountering a "Permission Denied" error when attempting to configure or run the test1-glb_15min.sh test case for the CaMa-Flood model. also showing some files are missing which is not attached to the downloaded folder(log_CaMa.txt)
![121](https://github.com/user-attachments/assets/7f622be8-ebd1-4045-8a29-936f43ab9bcd)
![2232](https://github.com/user-attachments/assets/c48e634b-65c9-4eab-81b6-9dc62b82d1a6)

**Comment by bigasmountain** [comment]
GitHub repository only contains "codes". To execute simulation, please download package from the CaMa-Flood webpage.

**Comment by siddigberama999** [comment]
Thanks for the response @bigasmountain it works fine, I just want to inquire whether I will be able to calculate 100,75,... flood return periods for both depth and inundation
