### ISSUE TITLE
High flood depth values

### ISSUE THREAD

**Issue by SepidehKhajehei** [global-hydrodynamics/CaMa-Flood_v4#88]
We have been using the CAMA flood model and recently generated several outputs, which are attached for your reference. As you can see in the visualizations, certain areas appear to lack significant variation, while others exhibit unexpected patterns, which may not align with the physical geography or known flood risk in these regions.
We are using the sample inputs from the e20-pcr-GLOBWB dataset that was provided as a sample for the model, and all inputs and parameters are set to their default values.

Specifically, we have noticed the following issues:

There are unexpectedly high flood depths in regions that are not typically prone to flooding.
The overall variability in flood depth across the domain appears lower than expected.
I would greatly appreciate your advice on how we might improve these results. Are there specific parameters or inputs that require closer attention or adjustments to better capture the physical characteristics of these regions?

The two plots attached below represent the Amazonian region and the Pacific Northwest in the United States.
![amazon](https://github.com/user-attachments/assets/2064e0f5-9e2b-488e-81db-99dd699a42a7)
![pacific](https://github.com/user-attachments/assets/83d95e5e-3d2c-4238-ac7a-5e4b23df6247)

Thank you for your time, and I look forward to your feedback.

**Comment by bigasmountain** [comment]
Flood depth becomes very high in rivers in mountains and gorge, when flush flood happens. I feel the results are reasonable. Please carefully examine the location
